version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "src/"
    schedule:
      interval: "weekly"
      day: "monday"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
