[package]
name = "boxer-validator-nginx"
version = "0.0.0"
edition = "2021"

[dependencies]
futures-util = "0.3.8"
anyhow = "1.0.86"
jwt-authorizer = "0.15.0"
log = "0.4.22"
env_logger = "0.11.5"
flate2 = "1.0"
base64 = "0.22.1"
boxer_core = { git = "https://github.com/SneaksAndData/boxer-core.git" }
serde_json = "1.0.140"
utoipa = { version = "5.3.1", features = ["actix_extras"] }
actix-web = "4.9.0"
cedar-policy = "4.4.0"
config = "0.15.11"
serde = { version = "1.0.207", features = ["derive"] }

[dev-dependencies]
rstest = "0.25.0"