[package]
name = "boxer-validator-nginx"
version = "0.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
actix-web = "4.9.0"
futures-util = "0.3.8"
jwt = "0.16.0"
opentelemetry-datadog = "0.12.0"
async-trait = "0.1.81"
anyhow = "1.0.86"
jwt-authorizer = "0.15.0"
log = "0.4.22"
env_logger = "0.11.5"


[dev-dependencies]
rstest = "0.22.0"
