# Application settings
instance_name = "integration-tests"

[backend]
# Kubernetes backend settings
[backend.kubernetes]
exec = "kind get kubeconfig --name kind" # Command to get kubeconfig for the Kind cluster
in_cluster = false                       # Whether to run in-cluster or not
namespace = "default"                    # Kubernetes namespace
lease_name = "boxer-validator"           # Name for the lease object
lease_duration = "60s"                   # Duration string for lease lifetime
lease_renew_duration = "15s"             # Duration string for lease renewal interval
