# Application settings
instance_name = "integration-tests"

listen_address = "127.0.0.1:8081"

[backend]
# Kubernetes backend settings
[backend.kubernetes]
exec = "kind get kubeconfig --name kind" # Command to get kubeconfig for the Kind cluster
in_cluster = false                       # Whether to run in-cluster or not
namespace = "default"                    # Kubernetes namespace
lease_name = "boxer-validator"           # Name for the lease object
lease_duration = "60s"                   # Duration string for lease lifetime
lease_renew_duration = "15s"             # Duration string for lease renewal interval
resource_owner_label = "local.debug"     # Label to identify resources created by this instance
operation_timeout = "30s"                # Timeout for operations on the backend operations

[opentelemetry.log_settings]
enabled = false

[opentelemetry.metrics_settings]
enabled = false

[opentelemetry.tracing_settings]
enabled = false

[token_settings]
keys = """
{
    "public": "0123456789ABCDEF0123456789ABCDEF"
}
"""
audience = "boxer.sneaksanddata.com" # Expected audience for tokens
issuer = "boxer.sneaksanddata.com" # Expected audience for tokens

