# Application settings
instance_name = "integration-tests"

[backend]
# Kubernetes backend settings
[backend.kubernetes]
exec = "kind get kubeconfig --name kind" # Command to get kubeconfig for the Kind cluster
namespace = "default"                    # Kubernetes namespace
lease_name = "boxer-validator"           # Name for the lease object
lease_duration = "60s"                   # Duration string for lease lifetime
lease_renew_duration = "15s"             # Duration string for lease renewal interval

# Repository settings for schemas
[backend.kubernetes.schema_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "validator-schema"