# Application settings
instance_name = "integration-tests"

[backend]
# Kubernetes backend settings
[backend.kubernetes]
exec = "kind get kubeconfig --name kind" # Command to get kubeconfig for the Kind cluster
in_cluster = false                       # Whether to run in-cluster or not
namespace = "default"                    # Kubernetes namespace
lease_name = "boxer-validator"           # Name for the lease object
lease_duration = "60s"                   # Duration string for lease lifetime
lease_renew_duration = "15s"             # Duration string for lease renewal interval

# Repository settings for schemas
[backend.kubernetes.schema_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "validator-schema"
name = "boxer-validator-schema"

[backend.kubernetes.actions_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "validator-actions"

[backend.kubernetes.resource_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "validator-resources"

[backend.kubernetes.policy_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "validator-policies"
