{{- if and .Values.rbac.clusterRole.leaseEditor.create .Values.rbac.clusterRoleBindings.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.clusteRole.leaseEditor" . }}
rules:
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]

{{- end }}
