apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "app.name" . }}
spec:
  maxUnavailable: {{ .Values.validator.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "app.name" . }}