apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "app.fullname" . }}-token-settings
  {{- with .Values.additionalAnnotations }}
  annotations:
        {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
type: Opaque
data:
  BOXER_VALIDATOR__TOKEN_SETTINGS__KEYS: {{ .Values.validator.config.tokenSettings.keys | b64enc | quote }}
