name: Run tests with coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  PROJECT_NAME: Boxer.Validator.Nginx
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  validate_commit:
    name: Validate Code and Publish Coverage
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # required for dependabot PRs
      pull-requests: write # required for dependabot PRs
      contents: read       # required for dependabot PRs
    steps:
      - uses: actions/checkout@v4
        
      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
        with:
         toolchain: stable
         components: rustfmt, clippy
         
      - name: Install just, cargo-llvm-cov, cargo-nextest
        uses: taiki-e/install-action@v2.50.10
        with:
          tool: cargo-llvm-cov

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
        
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
        
      - name: Upload coverage to Codecov
        uses: romeovs/lcov-reporter-action@v0.4.0
        with:
          lcov-file: ./lcov.info
